### ISSUE TITLE
All values are unknown

### ISSUE THREAD

**Issue by devpolly69** [a529987659852/openwb2mqtt#11]
Hello,

here definitely seems to be a problem with the timing when subscribing to MQTT topics here I get the following error in the log. The value is considered "unavailable" for this long. 
````
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:576
integration: Binary Sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 11:58:21 (3 occurrences)
Last logged: 11:58:21

Error adding entity binary_sensor.openwb_chargepoint_4_ladekabel for domain binary_sensor with platform openwb2mqtt
Error adding entity binary_sensor.openwb_chargepoint_4_autoladestatus for domain binary_sensor with platform openwb2mqtt
Error adding entity binary_sensor.openwb_chargepoint_4_fehler for domain binary_sensor with platform openwb2mqtt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/openwb2mqtt/binary_sensor.py", line 163, in async_added_to_hass
    await mqtt.async_subscribe(
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 173, in async_subscribe
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot subscribe to topic 'openWB/chargepoint/4/get/plug_state', MQTT is not enabled
````

After a short time the status changes to "unknown". It looks to me as if the subscription then worked. However, the values are not updated or any value is displayed. With the MQTT Explorer, however, I can see the values in HA-MQTT. 

![image](https://github.com/a529987659852/openwb2mqtt/assets/160501975/866e3443-e336-4dc2-8609-2f29b4a7b7d7)

MQTT-Explorer connected to HA-MQTT
![image](https://github.com/a529987659852/openwb2mqtt/assets/160501975/4e969874-cea2-444c-83c4-b2ce59b764ad)

I tried several configurations for mosquitto.conf but none of them worked. 

Thanks a lot for some help.

BR
Kub

**Comment by farbfoto** [comment]
I have unfortunately the same issue. Running external MQTT server...

**Comment by Saharel001** [comment]
same here with externe MQTT, but only the chargepoint sensors are missing: 
![image](https://github.com/a529987659852/openwb2mqtt/assets/24453343/0de02da6-222b-4168-b77c-5ed25900168f)

**Comment by Saharel001** [comment]
i maybe found the problem in the core.config_entries :

```
      {
        "entry_id": "af7d7e249a303e941d6ac9a5473ef93f",
        "version": 1,
        "minor_version": 1,
        "domain": "openwb2mqtt",
        "title": "openWB-controller",
        "data": {
          "mqttroot": "openWB",
          "DEVICETYPE": "chargepoint",
          "DEVICEID": 10
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "openWB-controller",
        "disabled_by": null
      }
```

I changed the DEVICETYPE manually from controller to chargepoint an after that i have got all informations from this topic. 
It look like not all sonsors will loaded correctly

**Comment by LostInTranslation2** [comment]
Same here. :-(

**Comment by ChoppedBeard** [comment]
i got the same problem because i'm still using OpenWB 1.9 firmware.
No more values when using this version. Sadly i cannot install the old one in HomeAssistant
https://github.com/a529987659852/openwbmqtt
